version: '3.8'

services:
  # backend services
  auth-service:
    build: ./server/auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./server/auth-service/.env
    restart: unless-stopped 

  dashboard-service:
    build: ./server/dashboard-service
    ports:
      - "3002:3002"
    env_file:
      - ./server/dashboard-service/.env
    restart: unless-stopped

  store-service:
    build: ./server/store-service
    ports:
      - "3003:3003"
    env_file:
      - ./server/store-service/.env
    restart: unless-stopped

  # frontend
  main-app:
    build: ./client/main-app
    ports:
      - "3000:3000"
  # For mapping our custom hostname 
    networks:
      default:
        aliases:
          - app.myplatform.local
    stdin_open: true

  dashboard-app:
    build: ./client/dashboard-app
    ports:
      - "4000:4000"
    networks:
      default:
        aliases:
          - dashboard.myplatform.local
    stdin_open: true

  store-app:
    build: ./client/store-app
    ports:
      - "5000:5000"
    networks:
      default:
        aliases:
          - store.myplatform.local
    stdin_open: true